// Curated IELTS idiom & phrase library. Static reference content —
// browsable and quizzable in the Idiom section. Sourced from the group's
// shared glossary.

export type Idiom = {
  word: string;
  meaning: string;
  example: string;
  category: string;
  band: string;
};

export const IDIOMS: Idiom[] = [
  {
    word: "an inexplicable sense of unease",
    meaning: "Perasaan gelisah yang tidak bisa dijelaskan — pengganti 'strange knot in my stomach'",
    example: "As the results were announced, an inexplicable sense of unease washed over me.",
    category: "Emotion & feeling",
    band: "7-8",
  },
  {
    word: "gaining traction",
    meaning: "Mulai diterima luas / mendapat momentum",
    example: "Remote working has been gaining traction among multinational corporations since 2020.",
    category: "Trends & change",
    band: "7",
  },
  {
    word: "develop in tandem",
    meaning: "Berkembang bersama secara sejajar — pengganti 'grow together / grow in step'",
    example: "Economic growth and environmental policy must develop in tandem to ensure sustainability.",
    category: "Relationships & comparison",
    band: "7-8",
  },
  {
    word: "profoundly disconcerting",
    meaning: "Sangat mengganggu/mengkhawatirkan — pengganti 'unsettle me the most'",
    example: "The rapid erosion of privacy norms in the digital age is profoundly disconcerting.",
    category: "Emotion & feeling",
    band: "7-8",
  },
  {
    word: "rise later than intended",
    meaning: "Bangun kesiangan secara formal — pengganti 'woke up late / slept in'",
    example: "On weekends, it is common for adolescents to rise later than intended, disrupting their sleep cycle.",
    category: "Time & routine",
    band: "6-7",
  },
  {
    word: "utterly sublime",
    meaning: "Sangat indah/luar biasa — pengganti 'tasted like heaven / absolutely divine'",
    example: "The cultural richness of the festival was utterly sublime, drawing visitors from across the globe.",
    category: "Emphasis & scale",
    band: "7-8",
  },
  {
    word: "a regular sparring partner",
    meaning: "Partner latihan/diskusi tetap — pengganti 'same person I played yesterday'",
    example: "Practising with a regular sparring partner accelerates skill development far more than solo drilling.",
    category: "Relationships & comparison",
    band: "7",
  },
  {
    word: "the defining moment",
    meaning: "Momen paling berkesan/menentukan — pengganti 'the highlight of my day'",
    example: "The professor's lecture on climate ethics proved to be the defining moment of the conference.",
    category: "Emphasis & scale",
    band: "7",
  },
  {
    word: "it is widely acknowledged that",
    meaning: "Sudah banyak diakui bahwa — cara formal menyatakan fakta umum tanpa 'I think'",
    example: "It is widely acknowledged that access to quality education remains the cornerstone of social mobility.",
    category: "Opinion & stance",
    band: "7-8",
  },
  {
    word: "a compelling case can be made for",
    meaning: "Ada argumen kuat yang mendukung — cara akademis menyatakan posisi",
    example: "A compelling case can be made for implementing a universal basic income in post-industrial economies.",
    category: "Opinion & stance",
    band: "7-8",
  },
  {
    word: "to a considerable extent",
    meaning: "Dalam tingkat yang cukup besar — pengganti 'very much' saat menyatakan persetujuan",
    example: "I agree, to a considerable extent, that technology has transformed the nature of human connection.",
    category: "Opinion & stance",
    band: "7",
  },
  {
    word: "the crux of the matter is",
    meaning: "Inti permasalahannya adalah — dipakai untuk mempertajam fokus argumen",
    example: "The crux of the matter is whether governments should prioritise economic growth over ecological preservation.",
    category: "Opinion & stance",
    band: "7-8",
  },
  {
    word: "that said,",
    meaning: "Walaupun demikian — transisi kontras yang natural dan akademis",
    example: "Exercise undeniably improves mental health. That said, it cannot serve as a substitute for professional therapy.",
    category: "Contrast & concession",
    band: "7",
  },
  {
    word: "notwithstanding this,",
    meaning: "Meskipun demikian — lebih formal dari 'however', sangat powerful di IELTS",
    example: "The policy has drawn criticism from economists. Notwithstanding this, public support remains remarkably high.",
    category: "Contrast & concession",
    band: "8",
  },
  {
    word: "on the flip side,",
    meaning: "Di sisi lain — lebih vivid dari 'on the other hand'",
    example: "Social media connects millions globally. On the flip side, it has been linked to rising rates of anxiety.",
    category: "Contrast & concession",
    band: "7",
  },
  {
    word: "the counterargument holds that",
    meaning: "Argumen sebaliknya menyatakan bahwa — cara akademis memperkenalkan pandangan berlawanan",
    example: "The counterargument holds that stricter gun laws infringe upon individual liberty.",
    category: "Contrast & concession",
    band: "7-8",
  },
  {
    word: "a far cry from",
    meaning: "Sangat berbeda dari — idiom kuat untuk menunjukkan kontras yang mencolok",
    example: "Living standards in rural areas remain a far cry from those enjoyed in urban centres.",
    category: "Emphasis & scale",
    band: "7",
  },
  {
    word: "the sheer scale of",
    meaning: "Besarnya skala — ekspresi yang menekankan ukuran yang luar biasa",
    example: "The sheer scale of plastic pollution in the Pacific Ocean defies comprehension.",
    category: "Emphasis & scale",
    band: "7-8",
  },
  {
    word: "nothing short of remarkable",
    meaning: "Tidak kurang dari luar biasa — cara band 8 memuji sebuah pencapaian",
    example: "The recovery of the ozone layer has been nothing short of remarkable.",
    category: "Emphasis & scale",
    band: "8",
  },
  {
    word: "at the heart of this issue lies",
    meaning: "Di inti permasalahan ini terletak — pembuka paragraf yang sangat kuat",
    example: "At the heart of this issue lies a fundamental tension between individual freedom and collective responsibility.",
    category: "Opinion & stance",
    band: "8",
  },
  {
    word: "an upward trajectory",
    meaning: "Tren meningkat — pengganti 'increased' yang lebih akademis untuk Task 1",
    example: "Renewable energy consumption has followed an upward trajectory since the Paris Agreement was signed.",
    category: "Trends & change",
    band: "7",
  },
  {
    word: "a marked shift towards",
    meaning: "Pergeseran yang jelas ke arah — menggantikan 'a change to'",
    example: "Recent decades have witnessed a marked shift towards remote and hybrid working arrangements.",
    category: "Trends & change",
    band: "7",
  },
  {
    word: "plateaued at",
    meaning: "Stagnan/mendatar di angka tertentu — sangat berguna di Task 1 graphs",
    example: "After years of rapid growth, the unemployment rate plateaued at approximately 4.5%.",
    category: "Trends & change",
    band: "7",
  },
  {
    word: "reached a peak of / bottomed out at",
    meaning: "Mencapai puncak / mencapai titik terendah — pasangan idiom wajib Task 1",
    example: "Exports reached a peak of $12 billion in 2019 before bottoming out at $7 billion during the pandemic.",
    category: "Trends & change",
    band: "7",
  },
  {
    word: "on a daily basis",
    meaning: "Setiap hari — pengganti 'every day' yang lebih formal",
    example: "Millions of commuters rely on public transport on a daily basis.",
    category: "Time & routine",
    band: "6-7",
  },
  {
    word: "in the long run",
    meaning: "Pada akhirnya / jangka panjang — idiom klasik yang disukai examiner",
    example: "Investing in early childhood education pays enormous dividends in the long run.",
    category: "Time & routine",
    band: "7",
  },
  {
    word: "an ingrained habit",
    meaning: "Kebiasaan yang sudah tertanam dalam — pengganti 'bad/good habit'",
    example: "Checking one's phone upon waking has become an ingrained habit among younger generations.",
    category: "Time & routine",
    band: "7",
  },
  {
    word: "it stands to reason that",
    meaning: "Sudah logis/masuk akal bahwa — cara elegan menyatakan kesimpulan logis",
    example: "It stands to reason that societies with stronger social safety nets experience lower crime rates.",
    category: "Opinion & stance",
    band: "7-8",
  },
  {
    word: "it is beyond dispute that",
    meaning: "Tidak dapat disangkal bahwa — lebih kuat dari 'it is clear that'",
    example: "It is beyond dispute that climate change poses an existential threat to coastal communities.",
    category: "Opinion & stance",
    band: "7-8",
  },
  {
    word: "the prevailing view is that",
    meaning: "Pandangan yang dominan adalah — cara akademis menyatakan konsensus umum",
    example: "The prevailing view is that early intervention in education yields the most significant long-term benefits.",
    category: "Opinion & stance",
    band: "7-8",
  },
  {
    word: "one cannot overlook the fact that",
    meaning: "Seseorang tidak bisa mengabaikan fakta bahwa — cara impersonal menekankan poin penting",
    example: "One cannot overlook the fact that poverty and lack of education are deeply interconnected.",
    category: "Emphasis & scale",
    band: "7",
  },
  {
    word: "bears testament to",
    meaning: "Menjadi bukti nyata dari — idiom kuat untuk mendukung klaim dengan bukti",
    example: "The rapid adoption of electric vehicles bears testament to growing public awareness of environmental issues.",
    category: "Emphasis & scale",
    band: "7-8",
  },
  {
    word: "a double-edged sword",
    meaning: "Pedang bermata dua — sesuatu yang memiliki keuntungan dan kerugian sekaligus",
    example: "Globalisation is often described as a double-edged sword, bringing prosperity while widening inequality.",
    category: "Contrast & concession",
    band: "7",
  },
  {
    word: "inextricably linked to",
    meaning: "Terkait erat dengan / tidak dapat dipisahkan dari",
    example: "Mental wellbeing is inextricably linked to physical health and social connection.",
    category: "Relationships & comparison",
    band: "7-8",
  },
  {
    word: "a watershed moment",
    meaning: "Momen titik balik yang sangat penting dan menentukan arah sejarah",
    example: "The invention of the internet marked a watershed moment in the history of human communication.",
    category: "Emphasis & scale",
    band: "7-8",
  },
  {
    word: "far outweighs",
    meaning: "Jauh lebih besar/penting dari — untuk membandingkan keuntungan vs kerugian",
    example: "The long-term benefit of vaccination far outweighs the risk of rare side effects.",
    category: "Relationships & comparison",
    band: "7",
  },
  {
    word: "with far-reaching consequences",
    meaning: "Dengan konsekuensi yang sangat luas — menekankan dampak yang besar",
    example: "The deforestation of the Amazon has accelerated with far-reaching consequences for global biodiversity.",
    category: "Emphasis & scale",
    band: "7-8",
  },
  {
    word: "a vicious cycle",
    meaning: "Lingkaran setan — masalah yang memperparah dirinya sendiri",
    example: "Poverty and poor education create a vicious cycle that is difficult for individuals to escape without external support.",
    category: "Relationships & comparison",
    band: "7",
  },
  {
    word: "it would be remiss to ignore",
    meaning: "Akan menjadi kelalaian jika mengabaikan — cara sopan tapi tegas menekankan suatu poin",
    example: "It would be remiss to ignore the role that government policy plays in exacerbating wealth inequality.",
    category: "Opinion & stance",
    band: "8",
  },
  {
    word: "not without its merits",
    meaning: "Tidak tanpa kelebihannya — cara balanced mengakui sisi positif argumen lawan",
    example: "The argument for stricter immigration controls is not without its merits, particularly from an economic standpoint.",
    category: "Contrast & concession",
    band: "7-8",
  },
  {
    word: "to put it another way,",
    meaning: "Dengan kata lain — transisi parafrase yang lebih elegan dari 'in other words'",
    example: "Access to clean water is a basic human right. To put it another way, denying it is a form of injustice.",
    category: "Contrast & concession",
    band: "7",
  },
  {
    word: "an unprecedented rate",
    meaning: "Laju yang belum pernah terjadi sebelumnya — untuk menekankan kecepatan perubahan",
    example: "Artificial intelligence is advancing at an unprecedented rate, transforming industries across the globe.",
    category: "Trends & change",
    band: "7",
  },
  {
    word: "showed a steep decline",
    meaning: "Menunjukkan penurunan yang tajam — Task 1 graph vocabulary",
    example: "Consumer confidence showed a steep decline in the third quarter following the interest rate hike.",
    category: "Trends & change",
    band: "7",
  },
  {
    word: "fluctuated considerably",
    meaning: "Berfluktuasi cukup signifikan — menggambarkan data yang naik turun di Task 1",
    example: "Oil prices fluctuated considerably throughout the decade, reflecting global geopolitical instability.",
    category: "Trends & change",
    band: "7",
  },
  {
    word: "accounted for the majority of",
    meaning: "Menyumbang sebagian besar dari — untuk Task 1 pie charts dan bar charts",
    example: "Transport emissions accounted for the majority of the city's total carbon output in 2022.",
    category: "Trends & change",
    band: "7",
  },
  {
    word: "in stark contrast to",
    meaning: "Sangat berbeda dari / berbanding terbalik dengan",
    example: "In stark contrast to developed nations, many low-income countries still lack reliable electricity infrastructure.",
    category: "Contrast & concession",
    band: "7",
  },
  {
    word: "broadly speaking,",
    meaning: "Secara garis besar — cara memperkenalkan generalisasi secara hati-hati",
    example: "Broadly speaking, countries with higher literacy rates tend to enjoy greater economic stability.",
    category: "Opinion & stance",
    band: "7",
  },
  {
    word: "it is imperative that",
    meaning: "Sangat penting/wajib bahwa — lebih kuat dari 'it is important that'",
    example: "It is imperative that policymakers address income inequality before social cohesion breaks down.",
    category: "Opinion & stance",
    band: "7-8",
  },
  {
    word: "serves as a stark reminder that",
    meaning: "Berfungsi sebagai pengingat keras bahwa — cara dramatis menarik kesimpulan",
    example: "The 2008 financial crisis serves as a stark reminder that deregulation carries systemic risks.",
    category: "Emphasis & scale",
    band: "7-8",
  },
  {
    word: "erode public trust",
    meaning: "Mengikis kepercayaan publik — kolokasi kuat untuk topik politik dan media",
    example: "Misinformation spread through social media continues to erode public trust in democratic institutions.",
    category: "Collocations",
    band: "7-8",
  },
  {
    word: "bridge the gap between",
    meaning: "Menjembatani jurang antara — kolokasi untuk ketimpangan dan perbedaan",
    example: "Technology alone cannot bridge the gap between the world's wealthiest and most disadvantaged populations.",
    category: "Collocations",
    band: "7",
  },
  {
    word: "exacerbate the problem",
    meaning: "Memperburuk masalah — lebih kuat dari 'make the problem worse'",
    example: "Cutting education budgets during a recession only serves to exacerbate the problem of youth unemployment.",
    category: "Collocations",
    band: "7",
  },
  {
    word: "pose a significant threat to",
    meaning: "Menimbulkan ancaman signifikan terhadap — kolokasi standar topik lingkungan/keamanan",
    example: "Rising sea levels pose a significant threat to low-lying island nations across the Pacific.",
    category: "Collocations",
    band: "7",
  },
  {
    word: "foster a sense of",
    meaning: "Menumbuhkan rasa/perasaan — kolokasi untuk topik komunitas dan pendidikan",
    example: "Team sports are well known to foster a sense of belonging and collective responsibility among participants.",
    category: "Collocations",
    band: "7",
  },
  {
    word: "alleviate poverty",
    meaning: "Mengurangi/meringankan kemiskinan — kolokasi baku topik sosial ekonomi",
    example: "Microfinancing has proven to be an effective tool to alleviate poverty in developing economies.",
    category: "Collocations",
    band: "6-7",
  },
  {
    word: "mitigate the impact of",
    meaning: "Mengurangi dampak dari — lebih akademis dari 'reduce the effect of'",
    example: "Urban green spaces can help mitigate the impact of extreme heat in densely populated cities.",
    category: "Collocations",
    band: "7",
  },
  {
    word: "undermine social cohesion",
    meaning: "Merusak kohesi sosial — kolokasi untuk topik imigrasi, ketimpangan, media",
    example: "Persistent inequality, if left unaddressed, will inevitably undermine social cohesion and political stability.",
    category: "Collocations",
    band: "7-8",
  },
  {
    word: "drive economic growth",
    meaning: "Mendorong pertumbuhan ekonomi — kolokasi wajib topik bisnis dan pembangunan",
    example: "Investment in infrastructure is widely regarded as one of the most reliable ways to drive economic growth.",
    category: "Collocations",
    band: "6-7",
  },
  {
    word: "it could be argued that",
    meaning: "Bisa diargumentasikan bahwa — cara hedging akademis yang menghindari klaim terlalu absolut",
    example: "It could be argued that the media bears partial responsibility for the rise in political polarisation.",
    category: "Opinion & stance",
    band: "7",
  },
  {
    word: "a nuanced perspective",
    meaning: "Perspektif yang bernuansa/kompleks — menunjukkan kemampuan berpikir kritis",
    example: "The debate around capital punishment requires a nuanced perspective that considers both justice and human rights.",
    category: "Opinion & stance",
    band: "7-8",
  },
  {
    word: "have a profound impact on",
    meaning: "Memiliki dampak yang mendalam terhadap — kolokasi kuat untuk menunjukkan pengaruh besar",
    example: "Early childhood experiences have a profound impact on an individual's cognitive and emotional development.",
    category: "Collocations",
    band: "7",
  },
  {
    word: "gain a competitive edge",
    meaning: "Mendapatkan keunggulan kompetitif — idiom bisnis yang relevan untuk topik pendidikan & ekonomi",
    example: "Nations that invest heavily in STEM education are better positioned to gain a competitive edge in the global economy.",
    category: "Collocations",
    band: "7",
  },
  {
    word: "the lion's share of",
    meaning: "Sebagian besar/porsi terbesar dari — idiom untuk menyatakan distribusi yang tidak merata",
    example: "Developed countries consume the lion's share of the world's natural resources.",
    category: "Emphasis & scale",
    band: "7",
  },
  {
    word: "tip the balance in favour of",
    meaning: "Menjadi faktor penentu yang memenangkan satu sisi — idiom untuk memutuskan argumen",
    example: "Strong empirical evidence may tip the balance in favour of renewable energy subsidies.",
    category: "Opinion & stance",
    band: "7-8",
  },
  {
    word: "in the foreseeable future",
    meaning: "Dalam waktu dekat yang dapat diprediksi — lebih formal dari 'soon'",
    example: "It is unlikely that fossil fuels will be phased out entirely in the foreseeable future.",
    category: "Time & routine",
    band: "7",
  },
  {
    word: "over the course of",
    meaning: "Selama / sepanjang kurun waktu — pengganti 'during' yang lebih formal",
    example: "Over the course of the past century, average global temperatures have risen significantly.",
    category: "Time & routine",
    band: "6-7",
  },
  {
    word: "in due course",
    meaning: "Pada waktunya / lambat laun — ekspresi waktu yang sopan dan formal",
    example: "The full consequences of artificial intelligence on the labour market will become clear in due course.",
    category: "Time & routine",
    band: "7",
  },
  {
    word: "the root cause of",
    meaning: "Penyebab mendasar dari — lebih kuat dari 'the reason for'",
    example: "Addressing the root cause of homelessness requires investment in mental health services and affordable housing.",
    category: "Relationships & comparison",
    band: "7",
  },
  {
    word: "the ripple effect of",
    meaning: "Efek riak/beruntun dari — dampak yang menyebar luas dari satu kejadian",
    example: "The collapse of a major bank can trigger the ripple effect of economic instability across multiple sectors.",
    category: "Relationships & comparison",
    band: "7-8",
  },
  {
    word: "lay the groundwork for",
    meaning: "Meletakkan fondasi untuk — idiom untuk persiapan jangka panjang",
    example: "Strong primary education lays the groundwork for a nation's long-term intellectual and economic development.",
    category: "Relationships & comparison",
    band: "7-8",
  },
  {
    word: "a contentious issue",
    meaning: "Isu yang kontroversial/diperdebatkan — pengganti 'a controversial topic'",
    example: "Capital punishment remains a contentious issue, dividing opinion across cultural and political lines.",
    category: "Opinion & stance",
    band: "7",
  },
  {
    word: "on the whole,",
    meaning: "Secara keseluruhan — pengganti 'overall' yang lebih natural untuk pembuka konklusi",
    example: "On the whole, the benefits of urban migration outweigh the social challenges it presents.",
    category: "Opinion & stance",
    band: "7",
  },
  {
    word: "strike a balance between",
    meaning: "Menemukan keseimbangan antara — idiom untuk solusi yang mengakomodasi dua sisi",
    example: "Effective governance must strike a balance between economic development and environmental protection.",
    category: "Relationships & comparison",
    band: "7",
  },
  {
    word: "call into question",
    meaning: "Mempertanyakan / menggugat — idiom untuk mengkritisi asumsi atau kebijakan",
    example: "Recent studies call into question the long-held belief that economic growth always reduces inequality.",
    category: "Opinion & stance",
    band: "7-8",
  },
  {
    word: "give rise to",
    meaning: "Menimbulkan / melahirkan — pengganti 'cause' atau 'lead to' yang lebih elegan",
    example: "Rapid urbanisation can give rise to a host of social problems, including overcrowding and unemployment.",
    category: "Trends & change",
    band: "7",
  },
  {
    word: "cast doubt on",
    meaning: "Menimbulkan keraguan terhadap — cara formal mempertanyakan validitas sesuatu",
    example: "The new evidence casts doubt on the effectiveness of zero-tolerance drug policies.",
    category: "Opinion & stance",
    band: "7-8",
  },
  {
    word: "without a shadow of a doubt",
    meaning: "Tanpa keraguan sedikit pun — cara menekankan keyakinan penuh di kalimat penutup",
    example: "Without a shadow of a doubt, education is the single most powerful tool for social transformation.",
    category: "Emphasis & scale",
    band: "7-8",
  },
];

export const IDIOM_CATEGORIES: string[] = Array.from(
  new Set(IDIOMS.map((i) => i.category))
).sort();
