// Auto-generated by scripts/gen-tables-sql.js. Do not edit by hand.
export const TABLE_SEEDS: { title: string; category: string; markdown: string }[] = [
  {
    "title": "Annual revenue of five retail chains in Indonesia (2020–2024, in billion IDR)",
    "category": "Retail",
    "markdown": "| Chain | 2020 | 2021 | 2022 | 2023 | 2024 |\n|---|---|---|---|---|---|\n| Alfamart | 85 | 92 | 101 | 110 | 125 |\n| Indomaret | 88 | 95 | 105 | 118 | 130 |\n| Transmart | 40 | 38 | 42 | 47 | 50 |\n| Ace Hardware | 15 | 17 | 19 | 22 | 26 |\n| Matahari | 30 | 25 | 28 | 32 | 35 |"
  },
  {
    "title": "Number of store branches opened by four e-commerce retailers in five cities",
    "category": "Retail",
    "markdown": "| Retailer | Jakarta | Surabaya | Bandung | Medan | Makassar |\n|---|---|---|---|---|---|\n| Shopee | 12 | 8 | 6 | 4 | 3 |\n| Tokopedia | 10 | 7 | 5 | 4 | 2 |\n| Lazada | 9 | 6 | 4 | 3 | 2 |\n| Blibli | 7 | 5 | 3 | 2 | 1 |"
  },
  {
    "title": "Customer satisfaction ratings (out of 10) for four supermarket chains across three regions",
    "category": "Retail",
    "markdown": "| Chain | Java | Sumatra | Kalimantan |\n|---|---|---|---|\n| Superindo | 8.2 | 7.5 | 7.8 |\n| Hypermart | 7.9 | 7.2 | 7.0 |\n| Giant | 6.8 | 6.5 | 6.2 |\n| Farmers Market | 8.5 | 8.0 | 7.9 |"
  },
  {
    "title": "Market share of retail categories (%): 2019, 2022, and 2024",
    "category": "Retail",
    "markdown": "| Category | 2019 | 2022 | 2024 |\n|---|---|---|---|\n| Fashion | 35 | 31 | 28 |\n| Electronics | 25 | 29 | 32 |\n| Groceries | 32 | 30 | 29 |\n| Home & Living | 8 | 10 | 11 |"
  },
  {
    "title": "Monthly sales of a retail company by channel (billion IDR, 6 months)",
    "category": "Retail",
    "markdown": "| Month | Online | Offline | Marketplace |\n|---|---|---|---|\n| Jan | 12 | 20 | 8 |\n| Feb | 13 | 19 | 9 |\n| Mar | 15 | 18 | 10 |\n| Apr | 18 | 17 | 12 |\n| May | 20 | 16 | 14 |\n| Jun | 23 | 15 | 16 |"
  },
  {
    "title": "Return on Equity (ROE) of four major Indonesian banks (2021–2025, %)",
    "category": "Banking",
    "markdown": "| Bank | 2021 | 2022 | 2023 | 2024 | 2025 |\n|---|---|---|---|---|---|\n| BCA | 17.4 | 18.0 | 18.5 | 19.2 | 19.8 |\n| BRI | 16.8 | 17.5 | 18.0 | 17.2 | 16.5 |\n| Mandiri | 15.2 | 16.8 | 18.1 | 19.5 | 20.1 |\n| BNI | 12.5 | 13.8 | 14.6 | 15.0 | 15.4 |"
  },
  {
    "title": "Non-Performing Loan (NPL) ratio of five banks across three countries (%)",
    "category": "Banking",
    "markdown": "| Bank | Country | NPL 2023 | NPL 2024 |\n|---|---|---|---|\n| Bank A | Indonesia | 2.6 | 2.4 |\n| Bank B | Indonesia | 3.4 | 3.1 |\n| Bank C | Malaysia | 2.0 | 1.8 |\n| Bank D | Thailand | 3.2 | 2.9 |\n| Bank E | Malaysia | 2.5 | 2.2 |"
  },
  {
    "title": "Total assets of the top five banks in Southeast Asia (USD billion): 2020, 2022, 2025",
    "category": "Banking",
    "markdown": "| Bank | 2020 | 2022 | 2025 |\n|---|---|---|---|\n| BCA | 70 | 82 | 95 |\n| Maybank | 180 | 195 | 210 |\n| DBS | 550 | 620 | 700 |\n| BRI | 140 | 165 | 190 |\n| CIMB | 150 | 160 | 175 |"
  },
  {
    "title": "Number of digital banking users for four banks (millions, 2021–2025)",
    "category": "Banking",
    "markdown": "| Bank | 2021 | 2022 | 2023 | 2024 | 2025 |\n|---|---|---|---|---|---|\n| BCA (BCA mobile) | 20 | 24 | 28 | 33 | 38 |\n| BRI (BRImo) | 15 | 19 | 24 | 30 | 36 |\n| Mandiri (Livin') | 12 | 16 | 21 | 27 | 33 |\n| BNI (wondr by BNI) | 9 | 13 | 18 | 23 | 29 |"
  },
  {
    "title": "Net Interest Margin (NIM) by bank ownership type in Indonesia (%)",
    "category": "Banking",
    "markdown": "| Year | State-owned | Private | Sharia |\n|---|---|---|---|\n| 2021 | 4.8 | 5.5 | 5.0 |\n| 2022 | 5.0 | 5.6 | 5.2 |\n| 2023 | 4.9 | 5.4 | 5.1 |\n| 2024 | 4.7 | 5.2 | 4.9 |\n| 2025 | 4.6 | 5.0 | 4.8 |"
  },
  {
    "title": "GDP growth rate of five ASEAN countries (2021–2025, %)",
    "category": "Economy",
    "markdown": "| Country | 2021 | 2022 | 2023 | 2024 | 2025 |\n|---|---|---|---|---|---|\n| Indonesia | 3.7 | 5.3 | 5.0 | 5.1 | 5.0 |\n| Vietnam | 2.6 | 8.0 | 5.1 | 6.2 | 6.5 |\n| Philippines | 5.7 | 7.6 | 5.5 | 5.8 | 6.0 |\n| Malaysia | 3.1 | 8.7 | 3.7 | 4.5 | 4.8 |\n| Thailand | 1.5 | 2.6 | 1.9 | 2.5 | 3.0 |"
  },
  {
    "title": "Inflation, unemployment, and BI interest rate in Indonesia (2021–2025, %)",
    "category": "Economy",
    "markdown": "| Year | Inflation | Unemployment | BI Rate |\n|---|---|---|---|\n| 2021 | 1.9 | 6.5 | 3.50 |\n| 2022 | 5.5 | 5.9 | 5.50 |\n| 2023 | 3.6 | 5.3 | 6.00 |\n| 2024 | 2.6 | 4.9 | 6.00 |\n| 2025 | 2.8 | 4.6 | 5.75 |"
  },
  {
    "title": "Foreign Direct Investment (FDI) inflows into four SEA countries (USD billion)",
    "category": "Economy",
    "markdown": "| Country | 2021 | 2022 | 2023 | 2024 |\n|---|---|---|---|---|\n| Indonesia | 20 | 22 | 25 | 28 |\n| Vietnam | 19 | 22 | 23 | 25 |\n| Singapore | 99 | 141 | 160 | 175 |\n| Malaysia | 12 | 15 | 17 | 19 |"
  },
  {
    "title": "Government spending by sector (% of GDP)",
    "category": "Economy",
    "markdown": "| Sector | 2021 | 2022 | 2023 | 2024 | 2025 |\n|---|---|---|---|---|---|\n| Education | 3.5 | 3.6 | 3.6 | 3.7 | 3.8 |\n| Health | 2.8 | 3.0 | 2.9 | 3.1 | 3.2 |\n| Infrastructure | 2.5 | 2.3 | 2.6 | 2.8 | 2.9 |\n| Social Protection | 3.0 | 3.2 | 3.4 | 3.5 | 3.6 |"
  },
  {
    "title": "Exchange rate of the Indonesian rupiah against three currencies (6 months)",
    "category": "Economy",
    "markdown": "| Month | IDR/USD | IDR/SGD | IDR/EUR |\n|---|---|---|---|\n| Jan | 15,850 | 11,750 | 17,200 |\n| Feb | 15,920 | 11,800 | 17,300 |\n| Mar | 16,100 | 11,900 | 17,450 |\n| Apr | 16,250 | 12,000 | 17,600 |\n| May | 16,400 | 12,100 | 17,750 |\n| Jun | 16,600 | 12,250 | 17,900 |"
  },
  {
    "title": "Internet, smartphone, and social media penetration in five countries (%)",
    "category": "Other",
    "markdown": "| Country | Internet | Smartphone | Social Media |\n|---|---|---|---|\n| Indonesia | 78 | 89 | 72 |\n| Vietnam | 80 | 85 | 75 |\n| Philippines | 74 | 80 | 71 |\n| Thailand | 85 | 91 | 78 |\n| Malaysia | 89 | 93 | 81 |"
  },
  {
    "title": "Number of new startups founded in four industries (2020–2025)",
    "category": "Other",
    "markdown": "| Industry | 2020 | 2021 | 2022 | 2023 | 2024 | 2025 |\n|---|---|---|---|---|---|---|\n| Fintech | 45 | 60 | 75 | 68 | 72 | 80 |\n| E-commerce | 38 | 50 | 65 | 55 | 58 | 62 |\n| Edtech | 20 | 35 | 48 | 40 | 38 | 42 |\n| Healthtech | 15 | 22 | 30 | 35 | 40 | 48 |"
  },
  {
    "title": "Renewable energy production by source in four countries (TWh)",
    "category": "Other",
    "markdown": "| Country | Solar | Hydro | Wind | Geothermal |\n|---|---|---|---|---|\n| Indonesia | 5 | 20 | 2 | 15 |\n| Vietnam | 15 | 25 | 10 | 0 |\n| Philippines | 3 | 10 | 2 | 12 |\n| Thailand | 8 | 5 | 3 | 0 |"
  },
  {
    "title": "Weekly working hours, minimum wage, and annual leave in five countries",
    "category": "Other",
    "markdown": "| Country | Weekly Hours | Min. Wage (USD/month) | Annual Leave (days) |\n|---|---|---|---|\n| Indonesia | 42 | 220 | 12 |\n| Vietnam | 45 | 190 | 12 |\n| Japan | 40 | 1,500 | 20 |\n| Germany | 34 | 2,100 | 30 |\n| United States | 38 | 1,600 | 10 |"
  },
  {
    "title": "Population growth, urbanization, and density of four major Indonesian cities",
    "category": "Other",
    "markdown": "| City | Population Growth (%) | Urbanization (%) | Density (people/km²) |\n|---|---|---|---|\n| Jakarta | 1.1 | 100 | 15,900 |\n| Surabaya | 0.9 | 95 | 8,500 |\n| Bandung | 1.3 | 88 | 15,000 |\n| Medan | 1.0 | 82 | 9,200 |"
  },
  {
    "title": "Export value of Indonesia's top five commodities (2021–2025, USD billion)",
    "category": "Other",
    "markdown": "| Commodity | 2021 | 2022 | 2023 | 2024 | 2025 |\n|---|---|---|---|---|---|\n| Palm Oil | 28 | 35 | 30 | 32 | 34 |\n| Coal | 25 | 45 | 35 | 30 | 28 |\n| Nickel products | 8 | 12 | 15 | 18 | 22 |\n| Textiles | 12 | 13 | 12 | 13 | 14 |\n| Rubber | 6 | 7 | 6 | 6 | 7 |"
  }
];
